### ISSUE TITLE
Suggestion: Submit a User Contributed Docset to Dash

### ISSUE THREAD

**Issue by xpe** [for-GET/know-your-http-well#35] opened 2015-03-13 04:12 UTC
Have you tried the following?

https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

It seems to be the recent process for user-contributed doc-sets.

**Comment by andreineculau** [comment] 2015-03-13 13:53
Duplicate of #31

**Closed by andreineculau** 2015-03-13 13:53 UTC
